id: I4C29DBB7
ocr_import_info:
  timestamp: '2023-06-27T16:25:48.138306+00:00'
  batch_id: batch-63cf
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-27 17:06:57.148981+00:00
last_modified: 2023-06-27 17:06:57.148986+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM188
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM188
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པ།
  languages:
  - bo
  author: པ་ཚབ་ལོ་ཙཱ་བ་ཉི་མ་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9516183776838186
  ocr_word_median_confidence_index: 0.9949362500000001
bases:
  I1NLM188_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM188_001
      total_pages: 207
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM188_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9949362500000001
      ocr_word_mean_confidence_index: 0.9516183776838186
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
